# Generated by Django 3.1.2 on 2020-10-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='')),
                ('barcode_kps', models.CharField(max_length=30)),
                ('barcode_manufacturer', models.CharField(max_length=50)),
            ],
        ),
    ]
