# Generated by Django 3.1.2 on 2020-10-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20201014_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('barcode_manufacturer', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='thing',
            name='barcode_kps',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='thing',
            name='barcode_manufacturer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='thing',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='FoodStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_app.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core_app.food')),
            ],
        ),
    ]
